#!/usr/bin/env python3
"""Build the MuleSoft API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Anypoint Platform': 'Anypoint',
    'Runtime Manager': 'Runtime Mgr',
}

LINES = [
    {
        "name": 'MuleSoft Anypoint',
        "color": '#00A0DF',
        "closed": True,
        "stations": [
        ('Platform', (640, 240)),
        ('Anypoint Platform', (831, 350)),
        ('Exchange', (831, 570)),
        ('Runtime Manager', (640, 680)),
        ('Anypoint MQ', (449, 570)),
        ('Design Center', (449, 350)),
        ],
    },
]

URL_OVERRIDES = {
    'Platform': 'https://apis.apis.io/apis/mulesoft/mulesoft/',
    'Anypoint Platform': 'https://apis.apis.io/apis/mulesoft/mulesoft-anypoint-platform-api/',
    'Exchange': 'https://apis.apis.io/apis/mulesoft/mulesoft-anypoint-exchange-api/',
    'Runtime Manager': 'https://apis.apis.io/apis/mulesoft/mulesoft-anypoint-runtime-manager-api/',
    'Anypoint MQ': 'https://apis.apis.io/apis/mulesoft/mulesoft-anypoint-mq-api/',
    'Design Center': 'https://apis.apis.io/apis/mulesoft/mulesoft-anypoint-design-center-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The MuleSoft API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: mulesoft/openapi · github.com/api-evangelist/mulesoft',
        out_dir=Path(__file__).resolve().parent,
        out_basename='mulesoft-subway-map',
        provider_id='mulesoft',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
